### ISSUE TITLE
No such method on 1.7.2

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/PlayTimeTracker#1]
```
Unhandled exception executing command 'ptt' in plugin PlayTimeTracker v0.1.12
org.bukkit.command.CommandException: Unhandled exception executing command 'ptt' in plugin PlayTimeTracker v0.1.12
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-1.7.2.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3023jnks]
        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:395) [Essentials.jar:?]
        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:380) [Essentials.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [craftbukkit-1.7.2.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3023jnks]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:175) [craftbukkit-1.7.2.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3023jnks]
        at org.bukkit.craftbukkit.v1_7_R1.CraftServer.dispatchCommand(CraftServer.java:683) [craftbukkit-1.7.2.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3023jnks]
        at net.minecraft.server.v1_7_R1.PlayerConnection.handleCommand(PlayerConnection.java:952) [craftbukkit-1.7.2.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3023jnks]
        at net.minecraft.server.v1_7_R1.PlayerConnection.a(PlayerConnection.java:814) [craftbukkit-1.7.2.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3023jnks]
        at net.minecraft.server.v1_7_R1.PacketPlayInChat.a(PacketPlayInChat.java:28) [craftbukkit-1.7.2.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3023jnks]
        at net.minecraft.server.v1_7_R1.PacketPlayInChat.handle(PacketPlayInChat.java:47) [craftbukkit-1.7.2.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3023jnks]
        at net.minecraft.server.v1_7_R1.NetworkManager.a(NetworkManager.java:146) [craftbukkit-1.7.2.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3023jnks]
        at net.minecraft.server.v1_7_R1.ServerConnection.c(SourceFile:134) [craftbukkit-1.7.2.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3023jnks]
        at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:655) [craftbukkit-1.7.2.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3023jnks]
        at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:250) [craftbukkit-1.7.2.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3023jnks]
        at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:545) [craftbukkit-1.7.2.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3023jnks]
        at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:457) [craftbukkit-1.7.2.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3023jnks]
        at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [craftbukkit-1.7.2.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3023jnks]
Caused by: java.lang.NoSuchMethodError: net.ess3.api.IEssentials.getUser(Ljava/util/UUID;)Lcom/earth2me/essentials/User;
        at cat.nyaa.playtimetracker.Main.isAFK(Main.java:78) ~[?:?]
        at cat.nyaa.playtimetracker.RecordMgr.updateSingle(RecordMgr.java:98) ~[?:?]
        at cat.nyaa.playtimetracker.Main.onCommand(Main.java:164) ~[?:?]        
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.7.2.jar:git-Bukkit-1.7.2-R0.3-2-g85f5776-b3023jnks]
        ... 16 more
```

**Comment by phoenixlzx** [comment]
Seems ok now.
