### ISSUE TITLE
1.16.3 support

### ISSUE THREAD

**Issue by JasonHorkles** [NyaaCat/PlayTimeTracker#19]
The plugin doesn't seem to work at all on paper 1.16.3. When a player attempts to do `/ptt`, it throws this error:
```
[10:11:06 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ptt' in plugin PlayTimeTracker v0.4.1
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.3.jar:git-Paper-206]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.3.jar:git-Paper-206]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1908) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1719) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-206]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-206]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.NoSuchMethodError: java.lang.Math.floorDiv(JI)J
        at cat.nyaa.playtimetracker.Locale.formatTime(Locale.java:31) ~[?:?]
        at cat.nyaa.playtimetracker.Main.printStatistic(Main.java:343) ~[?:?]
        at cat.nyaa.playtimetracker.Main.onCommand(Main.java:250) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.3.jar:git-Paper-206]
        ... 18 more
```

**Comment by ACZMUX** [comment]
I want it too

**Comment by nullXer0** [comment]
> Caused by: java.lang.NoSuchMethodError: java.lang.Math.floorDiv

That specific error is because you're running java 7 or earlier. Update java to fix the problem.

**Comment by JasonHorkles** [comment]
> > Caused by: java.lang.NoSuchMethodError: java.lang.Math.floorDiv
> 
> That specific error is because you're running java 7 or earlier. Update java to fix the problem.

Except we're using java 8
I compiled the plugin myself with and updated version of essx and it seems to work fine
